### ISSUE TITLE
How do I manually terminate access to this resource when online

### ISSUE THREAD

**Issue by ricruan** [globophobe/django-semantic-admin#107]
When accessing the admin page online, the browser will load the resource.
👇
https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js
👆
The page load must wait for the request to fail before it can complete

So offline loading is fast

Is this .JS file necessary？Is there a better solution?

load the file to load, or  Load this js file asynchronously with the page load?

**Comment by ricruan** [comment]
load the file to local...

**Comment by ricruan** [comment]
download the file to local nemed it 'jquery.min.js'
then put it to semantic_admin\static\semantic_admin
then update the code at semantic_admin\templates\admin\base.html
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
--->👇
<script src="{% static 'semantic_admin/jquery.min.js' %}"></script>

**Comment by globophobe** [comment]
Loading of resources could be improved. Actually, the other day I tried having all assets local (not using a CDN) but it seemed slower...

However, your experience is different 🤔
