### ISSUE TITLE
Add `django-filter` to dependency list

### ISSUE THREAD

**Issue by vrialland** [globophobe/django-semantic-admin#2]
Hi,

I created a new Django project, installed `django-semantic-admin` and added it in `INSTALLED_APPS` as described in the README.
On the first access to `/admin` a `ModuleNotFoundError` exception is raised:

```
ModuleNotFoundError: No module named 'django_filters'
```

As `django-filter` is used in two files (https://github.com/globophobe/django-semantic-admin/search?q=django_filters), I guess the library should be moved to Poetry's `dependencies` instead of `dev-dependencies` https://github.com/globophobe/django-semantic-admin/blob/3f71d25f4ed93894e5c610e9c6cb7d8b3e25fcb0/pyproject.toml#L29

**Comment by globophobe** [comment]
Hey thanks! 

Actually, it's a mistake, though. I think `django_filters` should be optional. 

The intention is that an admin with `filter_class` attr will have a search bar with the additional filters.

Def, should have some checks for the imports.

**Comment by vrialland** [comment]
OK, thanks for the feedback, I've closed the associated PR then :slightly_smiling_face:
