### ISSUE TITLE
Have no idea why my check all not work when using SemanticModelAdmin

### ISSUE THREAD

**Issue by r51303** [globophobe/django-semantic-admin#68]
As title, 
when I change my admin model to SemanticModelAdmin
my check all box is not working anyway.

- As image 

![image](https://user-images.githubusercontent.com/7407295/227703066-3d9c1d79-866e-4273-9509-081b0cfdd76f.png)

But, if using DefaultModelAdmin, check all work again.

- As image
![image](https://user-images.githubusercontent.com/7407295/227703904-87487746-a6c8-446b-98d3-2f2a22a6fecb.png)

Very hard to debug, 
because there is no console error in chrome and have not any error show up everywhere.

Please help me, thanks.

**Comment by globophobe** [comment]
There is no problem with the http://semantic-admin.com demo.

What Django version are you using?

**Comment by r51303** [comment]
> There is no problem with the http://semantic-admin.com demo.
> 
> What Django version are you using?

Hi, @globophobe 

Here is my django version

```
$ django-admin --version
4.1.7
```

**Comment by globophobe** [comment]
The demo is curently 4.1.6 The checkboxes require [semantic_admin/static/admin/js/actions.js](https://github.com/globophobe/django-semantic-admin/blob/main/semantic_admin/static/admin/js/actions.js)  to be loaded. 
In my local environment, I updated to Django 4.1.7 and ran the demo with `python manage.py runserver`.

Can you confirm that actions.js is loaded, as below?
![actions](https://user-images.githubusercontent.com/891192/227707278-a8afc93f-692c-4412-a9d3-7a60254242b9.png)

**Comment by r51303** [comment]
> The demo is curently 4.1.6 The checkboxes require [semantic_admin/static/admin/js/actions.js](https://github.com/globophobe/django-semantic-admin/blob/main/semantic_admin/static/admin/js/actions.js) to be loaded. In my local environment, I updated to Django 4.1.7 and ran the demo with `python manage.py runserver`.
> 
> Can you confirm that actions.js is loaded, as below? ![actions](https://user-images.githubusercontent.com/891192/227707278-a8afc93f-692c-4412-a9d3-7a60254242b9.png)

Awesome,
I check that file (action.js) is not load.
And find my static file have not seen that file.

So, 
I'm running command 
`$ python manage.py collectstatic`

And, ctrl+F5 refresh my web page.

It's working now!!

Thanks for helping me a lot.
