### ISSUE TITLE
button messed up with Django admin import/export

### ISSUE THREAD

**Issue by tushortz** [globophobe/django-semantic-admin#74]
Really love this Django admin theme. Clean and simple.

<img width="1103" alt="image" src="https://github.com/globophobe/django-semantic-admin/assets/13158672/37868772-28d3-456e-aaa3-b344ed3cf3cb">

I noticed the buttons is messed up when using external package like Django admin import / export

**Comment by globophobe** [comment]
Completely supporting django-import-export would require overriding all of the following templates https://github.com/django-import-export/django-import-export/tree/main/import_export/templates/admin/import_export

Is this issue limited to the change list button?

**Comment by tushortz** [comment]
yes so far thats the only place with the issue

**Comment by globophobe** [comment]
So, I took a look at it locally.  If the only issue is really just the button, and you don't mind the default form style, I'll push my changes. 

It seems fully supporting django-import-export would also mean overriding their forms https://github.com/django-import-export/django-import-export/blob/main/import_export/forms.py as well as their static files https://github.com/django-import-export/django-import-export/tree/main/import_export/static/import_export

django-import-export is a popular project, so I don't mind supporting it, but it seems like it might take time to fully support it.

Desktop:
![change-desktop](https://github.com/globophobe/django-semantic-admin/assets/891192/8939045c-fde4-4ed4-b946-154e74a1d2a2)

Mobile:
![change-list-mobile](https://github.com/globophobe/django-semantic-admin/assets/891192/b967fcd0-559c-4b19-b7c8-439ad6f184ad)

**Comment by tushortz** [comment]
this looks nice thanks.

**Comment by tushortz** [comment]
or maybe you can have a note in the readme on instructions on how to do the
override instead of modifying the repo and interested parties can follow
the instruction

**Comment by globophobe** [comment]
Sorry, for not pushing my changes yet. I’ve been working on this, but it’s a little involved…

**Comment by globophobe** [comment]
Was distracted by the holidays, and [this JS](https://github.com/django-import-export/django-import-export/blob/main/import_export/static/import_export/guess_format.js).

I'd never actually used django-import-export before. It's more interesting than I expected :smile: 

Just a little more and it should be OK for a release.

Import:
![import](https://github.com/globophobe/django-semantic-admin/assets/891192/acf8a6ee-c8bc-4a2e-961f-03d24046887f)

Export:
![export-action](https://github.com/globophobe/django-semantic-admin/assets/891192/3d8d2fdd-3904-4785-bc65-c47086a1d297)

**Comment by globophobe** [comment]
Pushed https://github.com/globophobe/django-semantic-admin/pull/76 and updated the demo environment. If there are no problems, merge and release
