### ISSUE TITLE
Clicking on the header checkbox does not select all other checkboxes

### ISSUE THREAD

**Issue by tushortz** [globophobe/django-semantic-admin#75]
Clicking the header checkbox doesnt select other checkboxes un the row like it does in the original Django admin template

![image](https://github.com/globophobe/django-semantic-admin/assets/13158672/8a7b0f8e-ea22-41fd-b9fa-3e5deb0bf751)

**Comment by globophobe** [comment]
Looking at the screenshot, the checkboxes don’t have Semantic UI style. Is the ModelAdmin a SemanticModelAdmin subclass?

I believe the demo, https://semantic-admin.com , shows the correct behavior

**Comment by globophobe** [comment]
Actually, this seems the same issue as https://github.com/globophobe/django-semantic-admin/issues/68

**Comment by tushortz** [comment]
i hadn't inherited from the semantic model admin but its working now for me

**Comment by tushortz** [comment]
thanks
