### ISSUE TITLE
Input type not defined on fields

### ISSUE THREAD

**Issue by captain828** [globophobe/django-semantic-admin#81]
It seems the input type isn't being set for most field types.
This partially breaks validation errors as inputs don't get the red background.

Only the "search" type has it (used in many-to-many rels).

**Comment by globophobe** [comment]
Thanks for reporting! I could confirm an issue with server side validation with required text fields in the https://semantic-admin.com demo. 

Is your issue also related to server side validation, or perhaps real time client side validation?

![validation](https://github.com/globophobe/django-semantic-admin/assets/891192/387dde10-f141-4110-86be-2d3793cac829)

**Comment by globophobe** [comment]
Maybe related to noNativeValidation option in as of yet unreleased FomanticUi 2.9.4 https://github.com/globophobe/django-semantic-admin/issues/63#issuecomment-1873049656

**Comment by captain828** [comment]
Server-side validation.

I looked at the code but don't know where the tags for the inputs are created as it seems that is the culprit.

**Comment by globophobe** [comment]
I believe the issue fixed in https://github.com/globophobe/django-semantic-admin/pull/82 The demo was updated with that branch, and if there are no problems I'll merge and release tomorrow or the day after

![text-input](https://github.com/globophobe/django-semantic-admin/assets/891192/b1be64d0-4188-49e6-8959-3b62ce0b36ff)

**Comment by globophobe** [comment]
Version 0.4.1 was released. Please let me know if this issue is resolved

**Comment by captain828** [comment]
I can confirm it's solved, thanks!
