### ISSUE TITLE
Django 5.1 compatibility

### ISSUE THREAD

**Issue by captain828** [globophobe/django-semantic-admin#98]
The deprecated filter `length_is` is used in the admin templates, specifically in `fieldset_content.html` but possibly elsewhere.
This filter was marked as deprecated in Django 4.2 and is removed from Django 5.1 onwards.

The fix would be to use the `length` filter instead.

**Comment by globophobe** [comment]
Hey, thanks for opening this issue! 

I think Django 5.1 is currently pre-release, so I assume this is not a bug affecting you in production.  I'll be updating django-semantic-admin closer to the release date of Django 5.1

**Comment by captain828** [comment]
Yeah, I opened this to track it for 5.1 as I tried it out and noticed the error in the admin pages.
